if(LUA_SOURCE_FOUND OR LUA_FOUND)
	SET (BUILD_MODULE 1)
	IF(NOT PROTOC_GEN_LUA_FOUND)
		SET(MODULE_NOTE "without protocol buffer support")
	ENDIF(NOT PROTOC_GEN_LUA_FOUND)
else()
	MESSAGE(STATUS "Disabling CheckLua since Lua was not found")
endif()
