if(LUA_SOURCE_FOUND OR LUA_FOUND)
    set(BUILD_MODULE 1)
    if(NOT PROTOC_GEN_LUA_FOUND)
        set(MODULE_NOTE "without protocol buffer support")
    endif(NOT PROTOC_GEN_LUA_FOUND)
else()
    message(STATUS "Disabling CheckLua since Lua was not found")
endif()
