# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "debian/jessie64"

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.provision "shell", inline: "sudo apt-get update -y"
  config.vm.provision "shell", inline: "sudo apt-get install -y git build-essential cmake debhelper"
  config.vm.provision "shell", inline: "sudo apt-get install -y python-dev libssl-dev libboost-all-dev libprotobuf-dev libcrypto++-dev libgtest-dev liblua5.1-0-dev"
  config.vm.provision "shell", inline: "sudo apt-get install -y protobuf-compiler python-protobuf"
  config.vm.provision "shell", inline: "sudo apt-get install -y mkdocs"



  # Provision build script
  config.vm.provision "shell", inline: "cp /etc/puppet/files/build-debian.sh /home/vagrant/build-debian.sh"
  config.vm.provision "shell", inline: "chmod 755 /home/vagrant/build-debian.sh"
  # Build NSClient++
  config.vm.provision "shell", inline: "su - vagrant -c ./build-debian.sh"

  config.vm.synced_folder "../../files", "/etc/puppet/files"
  config.vm.synced_folder "../../../", "/source/nscp"

  config.ssh.forward_agent = true
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.ssh.insert_key = false

  
end
