#!/bin/sh
set -e


if [ "$1" = "configure" ]; then

  if ! grep -q nsclient /etc/passwd; then
  	adduser --system --no-create-home nsclient
  	addgroup --system nsclient
  	adduser nsclient nsclient
  fi

    # Create log folder if it doesn't exist (redundancy check)
    mkdir -p /var/log/nsclient

    # Reload systemd to recognize the new service
    if command -v systemctl >/dev/null 2>&1; then
        systemctl daemon-reload

        # Enable and start the service (optional, policy dependent)
        systemctl enable nsclient
        systemctl start nsclient
    fi
fi
