SET(Boost_DEBUG 1)

set(Boost_USE_STATIC_LIBS   ON)
set(BOOST_USE_MULTITHREADED ON)

SET(BOOST_INCLUDEDIR c:/src/include/boost-1_39/)
SET(BOOST_LIBRARYDIR c:/src/lib/x86/)
SET(BOOST_LIB_SUFFIX vc80-mt)
SET(BOOST_LIB_VERSION 1.39)
