%define debug_package %{nil}

Summary:	Simple yet powerful and secure monitoring daemon originally built for Nagios/Icinga
Name:		@CPACK_PACKAGE_NAME@
Version:	@CPACK_PACKAGE_VERSION@
Release:	@CPACK_PACKAGE_RELEASE@
License:	GPLv2+
Group:		Applications/System
Vendor:         @CPACK_PACKAGE_VENDOR@
Prefix:         @CPACK_PACKAGING_INSTALL_PREFIX@
URL:		http://nsclient.org
Source0:	https://github.com/mickem/nscp/tree/master/releases/%{version}.tar.gz
BuildRoot:	@CMAKE_CURRENT_BINARY_DIR@/_CPack_Packages/Linux/RPM/@CPACK_PACKAGE_FILE_NAME@
Packager:	Pall Sigurdsson <palli@opensource.is>
Requires:	boost-filesystem boost-program-options boost-thread protobuf
BuildRequires:  cmake
BuildRequires:  python 
BuildRequires:  openssl-devel
BuildRequires:  boost-devel
BuildRequires:  python-devel
BuildRequires:  protobuf-devel
BuildRequires:  protobuf-compiler
BuildRequires:  rst2pdf 

%define _rpmdir @CMAKE_CURRENT_BINARY_DIR@/_CPack_Packages/Linux/RPM
%define _rpmfilename @CPACK_PACKAGE_FILE_NAME@.rpm
%define _unpackaged_files_terminate_build 0
%define _topdir @CMAKE_CURRENT_BINARY_DIR@/_CPack_Packages/Linux/RPM

%description
NSClient++ (nscp) aims to be a simple yet powerful and secure monitoring daemon. It was built for Nagios/Icinga, but nothing in the daemon is Nagios/Icinga specific and it can be used in many other scenarios where you want to receive/distribute check metrics.

# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT @CMAKE_CURRENT_BINARY_DIR@/_CPack_Packages/Linux/RPM/tmpBBroot

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -Rf $RPM_BUILD_ROOT
fi
mv "@CMAKE_CURRENT_BINARY_DIR@/_CPack_Packages/Linux/RPM/tmpBBroot" $RPM_BUILD_ROOT

mkdir -p %{buildroot}%{_exec_prefix}
mkdir -p %{buildroot}%{_sysconfdir} 
mkdir -p %{buildroot}%{_sysconfdir}/init.d/
 
install -D -p -m 0755 tmp/nscp %{buildroot}%{_exec_prefix}/sbin/nscp
install -m 0755 -p tmp/nsclient.ini %{buildroot}%{_sysconfdir}/nsclient.ini
install -m 0755 -p files/nscp.init %{buildroot}%{_sysconfdir}/init.d/nscp


%clean
rm -rf %{buildroot}

%post

%files
%defattr(-,root,root,-)
@CPACK_PACKAGING_INSTALL_PREFIX@/@LIB_INSTALL_DIR@/*
@CPACK_PACKAGING_INSTALL_PREFIX@/sbin/nscp
%doc README.md
%config(noreplace) %{_sysconfdir}/nsclient.ini
%{_sysconfdir}/init.d/nscp

%changelog
* Wed Oct 16 2013 Pall Sigurdsson <palli@opensource.is> 0.4.1-3
- Initial Packaging
