# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "puppetlabs/centos-6.5-64-puppet"
	config.vm.hostname = "centos65x64.build.nscp.org"

	config.vm.provider :virtualbox do |vb|
		vb.gui = false
		vb.customize ["modifyvm", :id, "--memory", "2048"]
		vb.cpus = 4
	end
	config.vm.provision "shell", inline: "mkdir -p /etc/puppet/modules;
				if [ ! -d /etc/puppet/modules/epel/ ]; then puppet module install stahnma-epel; fi;
				"

	config.vm.provision :puppet do |puppet|
		puppet.manifests_path = "../../redhat/manifests"
		puppet.manifest_file  = "base.pp"
	end

	config.vm.provision "shell", inline: "su - vagrant -c './build.sh -DBoost_NO_BOOST_CMAKE=ON'"

	config.vm.synced_folder "../../files", "/etc/puppet/files"
	config.vm.synced_folder "../../../", "/source/nscp"
	config.ssh.forward_agent = true
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.ssh.insert_key = false
  
end
