if(WIN32)
	if(VSTUDIO_EXPRESS)
		set(BUILD_MODULE_SKIP_REASON "Not supported on VIsual Studio Express")
	else(VSTUDIO_EXPRESS)
		set(BUILD_MODULE 1)
	endif(VSTUDIO_EXPRESS)
else(WIN32)
	set(BUILD_MODULE_SKIP_REASON "Not supported on Windows")
endif(WIN32)
