---
name: Run rest test
description: Validate that rest endpoints return expected results
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: tests/rest/package-lock.json

    - name: Install dependencies
      working-directory: tests/rest
      shell: bash
      run: npm install

    - name: Start NSClient++ (Windows)
      if: runner.os == 'Windows'
      working-directory: tmp/nscp
      shell: cmd
      run: |
        del nsclient.log
        cmd /c "start nscp test --settings ..\..\tests\rest\nsclient.ini"

    - name: Start NSClient++ (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        nscp test --settings tests/rest/nsclient.ini > /tmp/nsclient.log 2>&1 &

    - name: Run tests
      working-directory: tests/rest
      shell: bash
      run: npm run test

    - name: Show logs (Windows)
      working-directory: tmp/nscp
      if: always() && runner.os == 'Windows'
      shell: bash
      run: cat nsclient.log || true

    - name: Show logs (Linux)
      if: always() && runner.os == 'Linux'
      shell: bash
      run: cat /tmp/nsclient.log || true

    - name: Stop NSClient++ (Windows)
      if: always() && runner.os == 'Windows'
      working-directory: tmp/nscp
      shell: cmd
      run: taskkill /F /im nscp.exe

    - name: Stop NSClient++ (Linux)
      if: always() && runner.os == 'Linux'
      shell: bash
      run: pkill -f nscp || true

