# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "oracle64_64x"
	config.vm.box_url = "https://dl.dropbox.com/sh/yim9oyqajopoiqs/G-XIEmQJMb/oracle64-64.box"
	config.vm.hostname = "ora64x64.build.nscp.org"

	config.vm.provider :virtualbox do |vb|
		vb.gui = false
		vb.customize ["modifyvm", :id, "--memory", "1024"]
	end
	
	config.vm.provision "shell", inline: "sudo yum --disablerepo=epel update nss"
	
	
	config.vm.provision "shell", inline: "mkdir -p /etc/puppet/modules;
				if [ ! -d /etc/puppet/modules/epel/ ]; then puppet module install stahnma-epel; fi;
				"

	config.vm.provision :puppet do |puppet|
		puppet.manifests_path = "../redhat/manifests"
		puppet.manifest_file  = "base.pp"
	end

#	config.vm.provision "shell", inline: "su - vagrant -c ./build-protobuf.sh"
#	config.vm.provision "shell", inline: "su - vagrant -c ./build-cryptopp.sh"
	config.vm.provision "shell", inline: "su - vagrant -c ./build.sh"

	config.vm.synced_folder "../files", "/etc/puppet/files"
	config.vm.synced_folder "../../", "/source/nscp"
	config.ssh.forward_agent = true
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.ssh.insert_key = false
  
end
