---
name: Run installer test
description: Validate that installer generates the corrct config
runs:
  using: composite
  steps:

    - name: Install dependencies
      working-directory: tests/msi
      shell: cmd
      run: |
        pip install -r requirements.txt

    - name: Run tests
      working-directory: tmp/nscp
      shell: cmd
      run: |
        python ..\..\tests\msi\test-install.py
