# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.3"

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # Install dependencies
  config.vm.provision "shell", inline: "sudo yum install -y cmake python-devel openssl-devel boost-devel lua-devel redhat-lsb rpmdevtools"
  config.vm.provision "shell", inline: "sudo yum groupinstall -y 'Development Tools'"
  config.vm.provision "shell", inline: "sudo yum install -y epel-release"
  config.vm.provision "shell", inline: "sudo yum install --enablerepo=epel -y gtest-devel python-argparse.noarch"
  config.vm.provision "shell", inline: "sudo yum install -y mkdocs"
  config.vm.provision "shell", inline: "sudo yum install -y protobuf-devel protobuf-compiler protobuf-python cryptopp-devel python-jinja2"
  
  # Provision build script
  config.vm.provision "shell", inline: "cp /etc/puppet/files/build.sh /home/vagrant/build.sh"
  config.vm.provision "shell", inline: "chmod 755 /home/vagrant/build.sh"
  # Build NSClient++
  config.vm.provision "shell", inline: "su - vagrant -c './build.sh -DBoost_NO_BOOST_CMAKE=ON'"

  config.vm.synced_folder "../../files", "/etc/puppet/files"
  config.vm.synced_folder "../../../", "/source/nscp"
  config.ssh.forward_agent = true
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.ssh.insert_key = false
  
end
