---
name: Download TinyXml2
description: Download and cache TinyXml2
inputs:
  version:
    description: The TinyXml2 version to cache
    required: true
outputs:
  path:
    description: The path to the folder (windows \ format)
    value:  ${{ steps.path.outputs.path }}
  path_unix:
    description: The path to the folder (unix / format)
    value:  ${{ steps.path.outputs.path_unix }}
runs:
  using: composite
  steps:
    - id: cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-tinyxml2-${{ inputs.version }}
        path: |
          tmp/tinyxml2-${{ inputs.version }}
    - id: check
      shell: pwsh
      run: |
        if (Test-Path "tmp/tinyxml2-${{ inputs.version }}") {
          echo "exists=true" >> $env:GITHUB_OUTPUT
        } else {
          echo "exists=false" >> $env:GITHUB_OUTPUT
        }

    - name: Download
      if: steps.check.outputs.exists == 'false'
      run: |
        curl -L https://github.com/leethomason/tinyxml2/archive/refs/tags/%TINY_XML2_VERSION%.zip --output tinyxml2.zip
        7z x tinyxml2.zip
        del tinyxml2.zip
        dir
      working-directory: tmp
      shell: cmd


    - id: path
      run: |
        $path=$pwd.path
        $path_unix=$pwd.path.replace('\','/')
        echo "path=$path" >> $env:GITHUB_OUTPUT
        echo "path_unix=$path_unix" >> $env:GITHUB_OUTPUT
      shell: pwsh
      working-directory: tmp/tinyxml2-${{ inputs.version }}
