set(CURRENT_MODULE_NAME "NSCP.Plugin.CSharpSample")
if(NSCP_DOTNET_SUPPORTED)
    set(BUILD_MODULE 1)
else()
    set(BUILD_MODULE 0)
    set(BUILD_MODULE_SKIP_REASON ".NET / C++/CLI support not available")
endif()
